server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri\;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        default_type application/json;
        return 200 '{"status":"200 OK", "zone":"Layer2 TLS Active"}\n';
    }
}
